import type {Classification} from "../tenancy/workspace.js";
type Detector="EMAIL"|"PHONE"|"CPF"|"LITERAL";
export type EgressRule=Readonly<{ruleId:string;kind:"PII"|"SECRET"|"FORBIDDEN";detector:Detector;action:"MASK"|"BLOCK";pattern?:string}>;
export type EgressException=Readonly<{exceptionId:string;version:number;tenantId:string;workspaceId:string;providerKey:string;modelKey:string;piiTypes:readonly Detector[];owner:string;approver:string;validFrom:string;expiresAt:string}>;
type Json=null|boolean|number|string|Json[]|{[key:string]:Json};
export type PrepareEgressInput=Readonly<{requestId:string;tenantId:string;workspaceId:string;policyVersion:string;policyDecision:"ALLOW"|"DENY";classification:Classification;allowedClassifications:readonly Classification[];providerKey:string;modelKey:string;routeDecision:"ALLOW"|"DENY";maximumClassification:Classification;ruleVersion:number;payload:unknown;rules:readonly EgressRule[];exception?:EgressException;now?:string}>;
type Exception=EgressException;type Input=PrepareEgressInput;
export type EgressGuardResult=Readonly<{decision:"ALLOW"|"DENY";denyReasons:readonly string[];ruleVersion:number;detections:Readonly<Record<string,number>>;exceptionId?:string;payload?:Json}>;
const ranks:Readonly<Record<Classification,number>>={public:0,internal:1,confidential:2,restricted:3};
const dangerous=new Set(["authorization","cookie","token","secret","password","apikey"]);
const patterns:Readonly<Record<Exclude<Detector,"LITERAL">,RegExp>>={EMAIL:/\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b/giu,PHONE:/\b(?:\+?55\s?)?(?:\(?\d{2}\)?\s?)?9?\d{4}[-\s]?\d{4}\b/gu,CPF:/\b\d{3}\.?\d{3}\.?\d{3}-?\d{2}\b/gu};
const secretPatterns=[/\bBearer\s+[A-Za-z0-9._~+/=-]{8,}\b/giu,/-----BEGIN (?:RSA |EC )?PRIVATE KEY-----[\s\S]*?-----END (?:RSA |EC )?PRIVATE KEY-----/gu];
function deny(ruleVersion:number,reasons:readonly string[],detections:Record<string,number>={}):EgressGuardResult{return Object.freeze({decision:"DENY",denyReasons:Object.freeze([...new Set(reasons)]),ruleVersion,detections:Object.freeze({...detections})});}
function validException(input:PrepareEgressInput,now:number):boolean{const value=input.exception;if(!value)return false;const start=Date.parse(value.validFrom),end=Date.parse(value.expiresAt);return value.tenantId===input.tenantId&&value.workspaceId===input.workspaceId&&value.providerKey===input.providerKey&&value.modelKey===input.modelKey&&value.owner!==value.approver&&Number.isFinite(start)&&Number.isFinite(end)&&now>=start&&now<end&&end-start<=30*86400000&&value.piiTypes.every(type=>type!=="LITERAL");}
function cloneJson(value:unknown,depth:number,seen:WeakSet<object>):Json{if(depth>20)throw new Error("DEPTH");if(value===null||typeof value==="boolean"||typeof value==="string")return value;if(typeof value==="number"&&Number.isFinite(value))return value;if(typeof value!=="object")throw new Error("TYPE");if(seen.has(value))throw new Error("CYCLE");seen.add(value);if(Array.isArray(value)){const output=value.map(item=>cloneJson(item,depth+1,seen));seen.delete(value);return output;}if(Object.getPrototypeOf(value)!==Object.prototype&&Object.getPrototypeOf(value)!==null)throw new Error("TYPE");const output:Record<string,Json>={};for(const [key,item] of Object.entries(value)){if(dangerous.has(key.toLowerCase().replace(/[_-]/g,"")))throw new Error("DANGEROUS_KEY");output[key]=cloneJson(item,depth+1,seen);}seen.delete(value);return output;}
function transform(value:Json,rules:readonly EgressRule[],exception:Exception|undefined,detections:Record<string,number>):Json{if(typeof value==="string"){for(const pattern of secretPatterns){pattern.lastIndex=0;if(pattern.test(value)){detections.SECRET=(detections.SECRET??0)+1;throw new Error("SECRET");}}let output=value;for(const rule of rules.filter(item=>item.kind!=="PII")){if(rule.detector!=="LITERAL"||!rule.pattern)continue;if(output.includes(rule.pattern)){detections[rule.ruleId]=(detections[rule.ruleId]??0)+1;throw new Error(rule.kind);}}for(const detector of ["EMAIL","PHONE","CPF"] as const){const expression=patterns[detector];expression.lastIndex=0;const matches=output.match(expression);if(!matches?.length)continue;detections[detector]=(detections[detector]??0)+matches.length;const rule=rules.find(item=>item.kind==="PII"&&item.detector===detector);if(!rule)throw new Error("RULE_MISSING");const excepted=exception?.piiTypes.includes(detector)??false;if(rule.action==="BLOCK"&&!excepted)throw new Error("PII");expression.lastIndex=0;output=output.replace(expression,`[REDACTED:${detector}]`);}return output;}if(Array.isArray(value))return value.map(item=>transform(item,rules,exception,detections));if(value&&typeof value==="object")return Object.fromEntries(Object.entries(value).map(([key,item])=>[key,transform(item,rules,exception,detections)]));return value;}
export function prepareEgress(input:Input):EgressGuardResult{if(input.policyDecision!=="ALLOW"||input.routeDecision!=="ALLOW")return deny(input.ruleVersion,["EGRESS_AUTHORITY_DENIED"]);if(!input.allowedClassifications.includes(input.classification)||ranks[input.classification]>ranks[input.maximumClassification])return deny(input.ruleVersion,["EGRESS_CLASSIFICATION_DENIED"]);const now=Date.parse(input.now??new Date().toISOString());if(input.exception&&!validException(input,now))return deny(input.ruleVersion,["EGRESS_EXCEPTION_INVALID"]);let payload:Json;try{payload=cloneJson(input.payload,0,new WeakSet());if(Buffer.byteLength(JSON.stringify(payload),"utf8")>1024*1024)return deny(input.ruleVersion,["EGRESS_PAYLOAD_INVALID"]);}catch{return deny(input.ruleVersion,["EGRESS_PAYLOAD_INVALID"]);}const detections:Record<string,number>={};try{const redacted=transform(payload,input.rules,input.exception,detections);return Object.freeze({decision:"ALLOW",denyReasons:[],ruleVersion:input.ruleVersion,detections:Object.freeze(detections),...(input.exception?{exceptionId:input.exception.exceptionId}:{}),payload:redacted});}catch(error){return deny(input.ruleVersion,[String(error).includes("SECRET")?"EGRESS_SECRET_DETECTED":String(error).includes("FORBIDDEN")?"EGRESS_PATTERN_FORBIDDEN":"EGRESS_PII_BLOCKED"],detections);}}
