import {createHash} from "node:crypto";
import type {Classification} from "../tenancy/workspace.js";
export type PrincipalType="user"|"group"|"domain"|"public";
export type SourceAcl=Readonly<{principalType:PrincipalType;principalRef:string;permission:"read"}>;
export type ConnectorItem=Readonly<{externalId:string;externalVersion:string;observedAt:string;modifiedAt?:string;mediaType:string;classification:Classification;checksum?:string;acl:readonly SourceAcl[]}>;
export type ConnectorPage=Readonly<{items:readonly ConnectorItem[];nextCursor?:string;hasMore:boolean}>;
export type ConnectorDescriptor=Readonly<{adapterKey:string;adapterVersion:number;minimumOauthScopes:readonly string[];cursorSchemaVersion:number}>;
export interface SourceConnector{readonly descriptor:ConnectorDescriptor;validateConnection(input:Readonly<{credentialRef:string;grantedScopes:readonly string[]}>):Promise<void>;listPage(input:Readonly<{cursor?:string;pageSize:number;signal:AbortSignal}>):Promise<ConnectorPage>;health(signal:AbortSignal):Promise<"HEALTHY"|"DEGRADED">;}
const KEY=/^[a-z][a-z0-9._-]{0,63}$/;const SCOPE=/^[A-Za-z0-9:./_-]{1,160}$/;const REF=/^(vaultref:[a-z0-9._/-]+#[1-9][0-9]*)$/;
export function validateDescriptor(value:ConnectorDescriptor):void{if(!KEY.test(value.adapterKey)||!Number.isSafeInteger(value.adapterVersion)||value.adapterVersion<1||!Number.isSafeInteger(value.cursorSchemaVersion)||value.cursorSchemaVersion<1||value.minimumOauthScopes.length>32||new Set(value.minimumOauthScopes).size!==value.minimumOauthScopes.length||value.minimumOauthScopes.some(scope=>!SCOPE.test(scope)))throw new Error("CONNECTOR_DESCRIPTOR_INVALID");}
export function validateCredentialGrant(descriptor:ConnectorDescriptor,credentialRef:string,granted:readonly string[]):void{validateDescriptor(descriptor);if(!REF.test(credentialRef)||granted.length!==descriptor.minimumOauthScopes.length||!descriptor.minimumOauthScopes.every(scope=>granted.includes(scope)))throw new Error("CONNECTOR_SCOPE_DENIED");}
export function validatePage(page:ConnectorPage,maximumClassification:Classification):void{const rank={public:0,internal:1,confidential:2,restricted:3};if(page.items.length>500||page.hasMore!==Boolean(page.nextCursor)||Buffer.byteLength(page.nextCursor??"")>8192)throw new Error("CONNECTOR_PAGE_INVALID");for(const item of page.items){if(!item.externalId||item.externalId.length>512||!item.externalVersion||item.externalVersion.length>256||item.acl.length<1||item.acl.length>1000||rank[item.classification]>rank[maximumClassification]||item.acl.some(acl=>!(["user","group","domain","public"] as string[]).includes(acl.principalType)||acl.permission!=="read"||!acl.principalRef||acl.principalRef.length>512))throw new Error("CONNECTOR_ITEM_DENIED");}}
export function dedupeKey(input:Readonly<{tenantId:string;workspaceId:string;sourceId:string;adapterKey:string;item:ConnectorItem}>):string{return`sha256:${createHash("sha256").update([input.tenantId,input.workspaceId,input.sourceId,input.adapterKey,input.item.externalId,input.item.externalVersion,input.item.checksum??""].join("\0")).digest("hex")}`;}
export function cursorHash(cursor?:string):string|undefined{return cursor?`sha256:${createHash("sha256").update(cursor).digest("hex")}`:undefined;}
export function retryDelayMs(attempt:number,random:()=>number,retryAfterSeconds?:number):number{if(!Number.isInteger(attempt)||attempt<1||attempt>8)throw new Error("CONNECTOR_RETRY_EXHAUSTED");const cap=Math.min(300_000,1000*2**(attempt-1));const jitter=Math.floor(Math.max(0,Math.min(0.999999,random()))*cap);return retryAfterSeconds===undefined?jitter:Math.min(300_000,Math.max(jitter,retryAfterSeconds*1000));}
