BEGIN;
CREATE TABLE cost_ledger_entry(
 tenant_id uuid NOT NULL,workspace_id uuid NOT NULL,user_id uuid NOT NULL,entry_id uuid NOT NULL,request_id uuid NOT NULL,reservation_id uuid NOT NULL,provider_key text NOT NULL,model_key text NOT NULL,tool_id text,task_type text NOT NULL,
 policy_version text NOT NULL,catalog_version bigint NOT NULL CHECK(catalog_version>0),price_version bigint NOT NULL CHECK(price_version>0),currency char(3) NOT NULL CHECK(currency ~ '^[A-Z]{3}$'),estimated_minor bigint NOT NULL CHECK(estimated_minor>=0),actual_minor bigint,
 input_tokens bigint NOT NULL CHECK(input_tokens>=0),output_tokens bigint NOT NULL CHECK(output_tokens>=0),receipt_id text,state text NOT NULL CHECK(state IN('reserved','committed','released','expired','reconciliation_review')),occurred_at timestamptz NOT NULL,updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
 PRIMARY KEY(tenant_id,entry_id),UNIQUE(tenant_id,reservation_id),UNIQUE(tenant_id,receipt_id),FOREIGN KEY(tenant_id,workspace_id) REFERENCES iam_workspace(tenant_id,workspace_id) ON DELETE RESTRICT,FOREIGN KEY(tenant_id,user_id) REFERENCES iam_user(tenant_id,user_id) ON DELETE RESTRICT,
 CHECK(actual_minor IS NULL OR actual_minor>=0),CHECK((state='committed' AND receipt_id IS NOT NULL AND actual_minor IS NOT NULL) OR state<>'committed')
);
CREATE INDEX cost_ledger_cursor_idx ON cost_ledger_entry(tenant_id,workspace_id,occurred_at,entry_id);CREATE INDEX cost_ledger_dimensions_idx ON cost_ledger_entry(tenant_id,provider_key,model_key,currency,occurred_at);
CREATE FUNCTION enforce_cost_ledger_transition() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF OLD.state<>'reserved' OR NEW.tenant_id<>OLD.tenant_id OR NEW.entry_id<>OLD.entry_id OR NEW.reservation_id<>OLD.reservation_id OR NEW.estimated_minor<>OLD.estimated_minor OR NEW.currency<>OLD.currency OR NEW.price_version<>OLD.price_version OR NEW.state NOT IN('committed','released','expired','reconciliation_review') THEN RAISE EXCEPTION 'COST_LEDGER_TRANSITION_INVALID';END IF;RETURN NEW;END $$;CREATE TRIGGER cost_ledger_transition BEFORE UPDATE ON cost_ledger_entry FOR EACH ROW EXECUTE FUNCTION enforce_cost_ledger_transition();
CREATE TABLE cost_threshold_event(tenant_id uuid NOT NULL,event_id uuid NOT NULL,scope_type text NOT NULL,scope_id text NOT NULL,threshold integer NOT NULL CHECK(threshold IN(80,100)),percent integer NOT NULL CHECK(percent>=threshold),currency char(3) NOT NULL,policy_version text NOT NULL,occurred_at timestamptz NOT NULL,cooldown_until timestamptz NOT NULL,PRIMARY KEY(tenant_id,event_id),UNIQUE(tenant_id,scope_type,scope_id,threshold,cooldown_until),FOREIGN KEY(tenant_id) REFERENCES iam_tenant(tenant_id) ON DELETE RESTRICT);
GRANT SELECT,INSERT,UPDATE ON cost_ledger_entry TO domus_gateway_runtime;GRANT SELECT,INSERT ON cost_threshold_event TO domus_gateway_runtime;GRANT SELECT ON cost_ledger_entry,cost_threshold_event TO domus_audit_reader;
ALTER TABLE cost_ledger_entry ENABLE ROW LEVEL SECURITY;ALTER TABLE cost_ledger_entry FORCE ROW LEVEL SECURITY;ALTER TABLE cost_threshold_event ENABLE ROW LEVEL SECURITY;ALTER TABLE cost_threshold_event FORCE ROW LEVEL SECURITY;
CREATE POLICY cost_ledger_gateway ON cost_ledger_entry TO domus_gateway_runtime USING(tenant_id=domus_security.current_uuid('app.current_tenant_id') AND workspace_id=domus_security.current_uuid('app.current_workspace_id')) WITH CHECK(tenant_id=domus_security.current_uuid('app.current_tenant_id') AND workspace_id=domus_security.current_uuid('app.current_workspace_id'));
CREATE POLICY cost_ledger_reader ON cost_ledger_entry FOR SELECT TO domus_audit_reader USING(tenant_id=domus_security.current_uuid('app.current_tenant_id') AND workspace_id=domus_security.current_uuid('app.current_workspace_id'));
CREATE POLICY cost_threshold_gateway ON cost_threshold_event TO domus_gateway_runtime USING(tenant_id=domus_security.current_uuid('app.current_tenant_id')) WITH CHECK(tenant_id=domus_security.current_uuid('app.current_tenant_id'));CREATE POLICY cost_threshold_reader ON cost_threshold_event FOR SELECT TO domus_audit_reader USING(tenant_id=domus_security.current_uuid('app.current_tenant_id'));
INSERT INTO schema_migrations(version,description) VALUES(10,'V1-306 cost ledger aggregates and threshold events') ON CONFLICT(version) DO NOTHING;
COMMIT;
