BEGIN;
CREATE TABLE source_connection (
 tenant_id uuid NOT NULL,workspace_id uuid NOT NULL,connection_id uuid NOT NULL,source_id uuid NOT NULL,adapter_key text NOT NULL CHECK(adapter_key~'^[a-z][a-z0-9._-]{0,63}$'),adapter_version integer NOT NULL CHECK(adapter_version>0),credential_ref text NOT NULL CHECK(credential_ref~'^vaultref:[a-z0-9._/-]+#[1-9][0-9]*$'),granted_scopes text[] NOT NULL CHECK(cardinality(granted_scopes) BETWEEN 0 AND 32),state text NOT NULL CHECK(state IN('pending','ready','syncing','backoff','paused','revoked','dead_letter')),cursor_value text CHECK(octet_length(cursor_value)<=8192),cursor_version bigint NOT NULL DEFAULT 0 CHECK(cursor_version>=0),fencing_token bigint NOT NULL DEFAULT 0 CHECK(fencing_token>=0),lease_owner uuid,lease_expires_at timestamptz,attempt integer NOT NULL DEFAULT 0 CHECK(attempt BETWEEN 0 AND 8),next_retry_at timestamptz,last_sync_at timestamptz,last_error_code text CHECK(last_error_code~'^[A-Z][A-Z0-9_]{0,119}$'),version bigint NOT NULL DEFAULT 1 CHECK(version>0),created_at timestamptz NOT NULL DEFAULT clock_timestamp(),updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
 PRIMARY KEY(tenant_id,workspace_id,connection_id),UNIQUE(tenant_id,workspace_id,source_id),FOREIGN KEY(tenant_id,workspace_id,source_id) REFERENCES source_registry(tenant_id,workspace_id,source_id) ON DELETE RESTRICT,CHECK((lease_owner IS NULL)=(lease_expires_at IS NULL)),CHECK(state='syncing' OR lease_owner IS NULL)
);
CREATE TABLE connector_item_dedupe (tenant_id uuid NOT NULL,workspace_id uuid NOT NULL,source_id uuid NOT NULL,dedupe_key text NOT NULL CHECK(dedupe_key~'^sha256:[a-f0-9]{64}$'),metadata_hash text NOT NULL CHECK(metadata_hash~'^sha256:[a-f0-9]{64}$'),first_execution_id uuid NOT NULL,first_seen_at timestamptz NOT NULL,PRIMARY KEY(tenant_id,workspace_id,source_id,dedupe_key),FOREIGN KEY(tenant_id,workspace_id,source_id) REFERENCES source_registry(tenant_id,workspace_id,source_id) ON DELETE RESTRICT);
CREATE TABLE connector_dead_letter (tenant_id uuid NOT NULL,workspace_id uuid NOT NULL,dead_letter_id uuid NOT NULL,connection_id uuid NOT NULL,execution_id uuid NOT NULL,error_code text NOT NULL CHECK(error_code~'^[A-Z][A-Z0-9_]{0,119}$'),error_hash text NOT NULL CHECK(error_hash~'^sha256:[a-f0-9]{64}$'),attempts integer NOT NULL CHECK(attempts BETWEEN 1 AND 8),state text NOT NULL CHECK(state IN('pending','requeued','discarded')),justification text CHECK(justification IS NULL OR char_length(btrim(justification)) BETWEEN 1 AND 500),created_at timestamptz NOT NULL,expires_at timestamptz NOT NULL,PRIMARY KEY(tenant_id,workspace_id,dead_letter_id),FOREIGN KEY(tenant_id,workspace_id,connection_id) REFERENCES source_connection(tenant_id,workspace_id,connection_id) ON DELETE RESTRICT,CHECK(expires_at>created_at));
CREATE TABLE connector_sync_outbox (tenant_id uuid NOT NULL,workspace_id uuid NOT NULL,event_id uuid NOT NULL,event_type text NOT NULL CHECK(event_type IN('source.sync.started.v1','source.sync.page_completed.v1','source.sync.completed.v1','source.sync.failed.v1','source.sync.paused.v1','source.sync.dead_lettered.v1')),request_id uuid NOT NULL,connection_id uuid NOT NULL,source_id uuid NOT NULL,execution_id uuid NOT NULL,source_version bigint NOT NULL,connection_version bigint NOT NULL,cursor_hash text CHECK(cursor_hash~'^sha256:[a-f0-9]{64}$'),item_count integer NOT NULL DEFAULT 0 CHECK(item_count BETWEEN 0 AND 500),error_code text,occurred_at timestamptz NOT NULL,attributes jsonb NOT NULL DEFAULT '{}'::jsonb,published_at timestamptz,delivery_attempts integer NOT NULL DEFAULT 0 CHECK(delivery_attempts>=0),PRIMARY KEY(tenant_id,workspace_id,event_id),FOREIGN KEY(tenant_id,workspace_id,connection_id) REFERENCES source_connection(tenant_id,workspace_id,connection_id) ON DELETE RESTRICT);
CREATE OR REPLACE FUNCTION pause_source_connection_when_ineligible() RETURNS trigger LANGUAGE plpgsql SECURITY INVOKER SET search_path=pg_catalog,public AS $$ BEGIN IF NEW.status<>'active' THEN UPDATE source_connection SET state='paused',lease_owner=NULL,lease_expires_at=NULL,last_error_code='SOURCE_INELIGIBLE',version=version+1,updated_at=clock_timestamp() WHERE tenant_id=NEW.tenant_id AND workspace_id=NEW.workspace_id AND source_id=NEW.source_id AND state NOT IN('paused','revoked'); END IF;RETURN NEW;END $$;
CREATE TRIGGER source_connection_source_state AFTER UPDATE OF status ON source_registry FOR EACH ROW WHEN(OLD.status IS DISTINCT FROM NEW.status) EXECUTE FUNCTION pause_source_connection_when_ineligible();
REVOKE ALL ON source_connection,connector_item_dedupe,connector_dead_letter,connector_sync_outbox FROM PUBLIC;GRANT SELECT,INSERT,UPDATE ON source_connection,connector_dead_letter TO domus_identity_runtime;GRANT SELECT,INSERT ON connector_item_dedupe,connector_sync_outbox TO domus_identity_runtime;
ALTER TABLE source_connection ENABLE ROW LEVEL SECURITY;ALTER TABLE source_connection FORCE ROW LEVEL SECURITY;ALTER TABLE connector_item_dedupe ENABLE ROW LEVEL SECURITY;ALTER TABLE connector_item_dedupe FORCE ROW LEVEL SECURITY;ALTER TABLE connector_dead_letter ENABLE ROW LEVEL SECURITY;ALTER TABLE connector_dead_letter FORCE ROW LEVEL SECURITY;ALTER TABLE connector_sync_outbox ENABLE ROW LEVEL SECURITY;ALTER TABLE connector_sync_outbox FORCE ROW LEVEL SECURITY;
CREATE POLICY source_connection_scope ON source_connection TO domus_identity_runtime USING(tenant_id=domus_security.current_uuid('app.current_tenant_id') AND workspace_id=domus_security.current_uuid('app.current_workspace_id')) WITH CHECK(tenant_id=domus_security.current_uuid('app.current_tenant_id') AND workspace_id=domus_security.current_uuid('app.current_workspace_id'));
CREATE POLICY connector_dedupe_scope ON connector_item_dedupe TO domus_identity_runtime USING(tenant_id=domus_security.current_uuid('app.current_tenant_id') AND workspace_id=domus_security.current_uuid('app.current_workspace_id')) WITH CHECK(tenant_id=domus_security.current_uuid('app.current_tenant_id') AND workspace_id=domus_security.current_uuid('app.current_workspace_id'));
CREATE POLICY connector_dead_letter_scope ON connector_dead_letter TO domus_identity_runtime USING(tenant_id=domus_security.current_uuid('app.current_tenant_id') AND workspace_id=domus_security.current_uuid('app.current_workspace_id')) WITH CHECK(tenant_id=domus_security.current_uuid('app.current_tenant_id') AND workspace_id=domus_security.current_uuid('app.current_workspace_id'));
CREATE POLICY connector_sync_outbox_scope ON connector_sync_outbox TO domus_identity_runtime USING(tenant_id=domus_security.current_uuid('app.current_tenant_id') AND workspace_id=domus_security.current_uuid('app.current_workspace_id')) WITH CHECK(tenant_id=domus_security.current_uuid('app.current_tenant_id') AND workspace_id=domus_security.current_uuid('app.current_workspace_id'));
INSERT INTO schema_migrations(version,description)VALUES(12,'V1-402 connector cursor, fencing, dedupe and dead-letter')ON CONFLICT(version)DO NOTHING;
COMMIT;
