BEGIN;
CREATE TABLE source_registry (
 source_id uuid NOT NULL,tenant_id uuid NOT NULL,workspace_id uuid NOT NULL,name text NOT NULL CHECK(char_length(btrim(name)) BETWEEN 1 AND 160),purpose text NOT NULL CHECK(char_length(btrim(purpose)) BETWEEN 1 AND 1000),
 source_type text NOT NULL CHECK(source_type ~ '^[a-z][a-z0-9._-]{0,63}$'),origin_system_key text NOT NULL CHECK(origin_system_key ~ '^[a-z][a-z0-9._-]{0,63}$'),connector_key text NOT NULL CHECK(connector_key ~ '^[a-z][a-z0-9._-]{0,63}$'),
 owner_user_id uuid,owner_acceptance text NOT NULL DEFAULT 'pending' CHECK(owner_acceptance IN('pending','accepted')),classification text CHECK(classification IN('public','internal','confidential','restricted')),
 schedule_mode text NOT NULL CHECK(schedule_mode IN('manual','scheduled')),sync_interval_seconds integer CHECK((schedule_mode='manual' AND sync_interval_seconds IS NULL) OR (schedule_mode='scheduled' AND sync_interval_seconds BETWEEN 300 AND 2592000)),
 freshness_sla_seconds integer NOT NULL CHECK(freshness_sla_seconds BETWEEN 300 AND 31536000),retention_days integer NOT NULL CHECK(retention_days BETWEEN 1 AND 3650),
 status text NOT NULL CHECK(status IN('draft','pending_owner','pending_review','active','paused','disconnected','archived')),status_reason text CHECK(status_reason IS NULL OR char_length(btrim(status_reason)) BETWEEN 1 AND 500),version bigint NOT NULL DEFAULT 1 CHECK(version>0),created_at timestamptz NOT NULL,updated_at timestamptz NOT NULL,
 PRIMARY KEY(tenant_id,workspace_id,source_id),FOREIGN KEY(tenant_id,workspace_id) REFERENCES iam_workspace(tenant_id,workspace_id) ON DELETE RESTRICT,FOREIGN KEY(tenant_id,workspace_id,owner_user_id) REFERENCES iam_workspace_membership(tenant_id,workspace_id,user_id) ON DELETE RESTRICT,
 CHECK(owner_acceptance='pending' OR owner_user_id IS NOT NULL),CHECK(status<>'active' OR (owner_user_id IS NOT NULL AND owner_acceptance='accepted' AND classification IS NOT NULL))
);
CREATE INDEX source_registry_updated_idx ON source_registry(tenant_id,workspace_id,updated_at DESC,source_id);
CREATE TABLE source_registry_audit (tenant_id uuid NOT NULL,workspace_id uuid NOT NULL,audit_id uuid NOT NULL,request_id uuid NOT NULL,actor_id uuid NOT NULL,source_id uuid NOT NULL,source_version bigint NOT NULL CHECK(source_version>0),operation text NOT NULL,attributes jsonb NOT NULL,occurred_at timestamptz NOT NULL,PRIMARY KEY(tenant_id,workspace_id,audit_id),FOREIGN KEY(tenant_id,workspace_id,source_id) REFERENCES source_registry(tenant_id,workspace_id,source_id) ON DELETE RESTRICT,FOREIGN KEY(tenant_id,actor_id) REFERENCES iam_user(tenant_id,user_id) ON DELETE RESTRICT);
CREATE TABLE source_registry_outbox (tenant_id uuid NOT NULL,workspace_id uuid NOT NULL,event_id uuid NOT NULL,event_type text NOT NULL CHECK(event_type IN('source.created.v1','source.submitted.v1','source.owner_accepted.v1','source.activated.v1','source.paused.v1','source.disconnected.v1','source.archived.v1')),request_id uuid NOT NULL,actor_id uuid NOT NULL,source_id uuid NOT NULL,source_version bigint NOT NULL CHECK(source_version>0),classification text CHECK(classification IN('public','internal','confidential','restricted')),status text NOT NULL,occurred_at timestamptz NOT NULL,attributes jsonb NOT NULL DEFAULT '{}'::jsonb,published_at timestamptz,delivery_attempts integer NOT NULL DEFAULT 0 CHECK(delivery_attempts>=0),PRIMARY KEY(tenant_id,workspace_id,event_id),FOREIGN KEY(tenant_id,workspace_id,source_id) REFERENCES source_registry(tenant_id,workspace_id,source_id) ON DELETE RESTRICT,FOREIGN KEY(tenant_id,actor_id) REFERENCES iam_user(tenant_id,user_id) ON DELETE RESTRICT);
REVOKE ALL ON source_registry,source_registry_audit,source_registry_outbox FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE ON source_registry TO domus_identity_runtime;GRANT SELECT,INSERT ON source_registry_audit,source_registry_outbox TO domus_identity_runtime;
ALTER TABLE source_registry ENABLE ROW LEVEL SECURITY;ALTER TABLE source_registry FORCE ROW LEVEL SECURITY;ALTER TABLE source_registry_audit ENABLE ROW LEVEL SECURITY;ALTER TABLE source_registry_audit FORCE ROW LEVEL SECURITY;ALTER TABLE source_registry_outbox ENABLE ROW LEVEL SECURITY;ALTER TABLE source_registry_outbox FORCE ROW LEVEL SECURITY;
CREATE POLICY source_registry_scope ON source_registry TO domus_identity_runtime USING(tenant_id=domus_security.current_uuid('app.current_tenant_id') AND workspace_id=domus_security.current_uuid('app.current_workspace_id')) WITH CHECK(tenant_id=domus_security.current_uuid('app.current_tenant_id') AND workspace_id=domus_security.current_uuid('app.current_workspace_id'));
CREATE POLICY source_registry_audit_scope ON source_registry_audit TO domus_identity_runtime USING(tenant_id=domus_security.current_uuid('app.current_tenant_id') AND workspace_id=domus_security.current_uuid('app.current_workspace_id')) WITH CHECK(tenant_id=domus_security.current_uuid('app.current_tenant_id') AND workspace_id=domus_security.current_uuid('app.current_workspace_id'));
CREATE POLICY source_registry_outbox_scope ON source_registry_outbox TO domus_identity_runtime USING(tenant_id=domus_security.current_uuid('app.current_tenant_id') AND workspace_id=domus_security.current_uuid('app.current_workspace_id')) WITH CHECK(tenant_id=domus_security.current_uuid('app.current_tenant_id') AND workspace_id=domus_security.current_uuid('app.current_workspace_id'));
INSERT INTO schema_migrations(version,description) VALUES(11,'V1-401 governed Source Registry and lifecycle outbox') ON CONFLICT(version) DO NOTHING;
COMMIT;
