import type {ModelCapability} from "../../domain/catalog/model-router.js";import type {BudgetScopeType} from "../../domain/budget/budget.js";
export type GatewayMessage=Readonly<{role:"system"|"user"|"assistant";content:string}>;
export type ModelGatewayCommand=Readonly<{tenantId:string;workspaceId:string;userId:string;deviceId:string;sessionId:string;requestId:string;idempotencyKey:string;task:string;messages:readonly GatewayMessage[];requiredCapabilities:readonly ModelCapability[];inputTokens:number;maximumOutputTokens:number;scopeKeys:readonly Readonly<{scopeType:BudgetScopeType;scopeId:string}>[]}>;
type Policy=Readonly<{policyVersion:string;classification:string;allowedModels:readonly string[];allowedClassifications:readonly string[];budgetScope:Readonly<{currency:string;remainingMinor:number}>;decision:"ALLOW"|"DENY"}>;
type Route=Readonly<{decision:"ALLOW"|"DENY";denyReasons?:readonly string[];modelKey?:string;providerKey?:string;catalogVersion?:number;priceVersion?:number;currency?:string;maximumEstimatedCostMinor?:number}>;
type Egress=Readonly<{decision:"ALLOW"|"DENY";denyReasons?:readonly string[];payload?:Readonly<{messages:readonly GatewayMessage[]}>;ruleVersion?:number}>;
type Dependencies=Readonly<{policy:{resolve(context:Pick<ModelGatewayCommand,"tenantId"|"workspaceId"|"userId"|"deviceId"|"sessionId"|"requestId">):Promise<Policy>};router:{route(input:Readonly<Record<string,unknown>>):Promise<Route>};egress:{prepare(input:Readonly<Record<string,unknown>>):Promise<Egress>};budget:{reserve(input:Readonly<Record<string,unknown>>):Promise<{reservationId:string;state:string}>;reconcile(input:Readonly<Record<string,unknown>>):Promise<{state:string}>};credential:{use<T>(providerKey:string,operation:(secret:string)=>Promise<T>):Promise<T>};provider:{invoke(input:Readonly<{providerKey:string;modelKey:string;messages:readonly GatewayMessage[];secret:string;requestId:string}>):Promise<{text:string;receiptId:string;actualMinor:bigint}>};audit:{record(input:Readonly<Record<string,unknown>>):Promise<void>}}>;
function denied(code:string):never{throw new Error(code);}
export async function executeModelRequest(dependencies:Dependencies,command:ModelGatewayCommand){
 if(!command.messages.length||command.messages.some(value=>!value.content)||command.idempotencyKey.length<16||command.idempotencyKey.length>128)denied("GATEWAY_REQUEST_INVALID");
 const context={tenantId:command.tenantId,workspaceId:command.workspaceId,userId:command.userId,deviceId:command.deviceId,sessionId:command.sessionId,requestId:command.requestId};
 const policy=await dependencies.policy.resolve(context);if(policy.decision!=="ALLOW")denied("POLICY_DENIED");
 const route=await dependencies.router.route({...context,policyVersion:policy.policyVersion,classification:policy.classification,allowedModels:policy.allowedModels,allowedClassifications:policy.allowedClassifications,requiredCapabilities:command.requiredCapabilities,inputTokens:command.inputTokens,maximumOutputTokens:command.maximumOutputTokens,budget:{currency:policy.budgetScope.currency,maximumCostMinor:policy.budgetScope.remainingMinor}});if(route.decision!=="ALLOW"||!route.modelKey||!route.providerKey||!route.priceVersion||!route.currency||route.maximumEstimatedCostMinor===undefined)denied("ROUTE_DENIED");
 const egress=await dependencies.egress.prepare({...context,policyVersion:policy.policyVersion,classification:policy.classification,providerKey:route.providerKey,modelKey:route.modelKey,payload:{messages:command.messages}});if(egress.decision!=="ALLOW"||!egress.payload)denied("EGRESS_DENIED");
 const reservation=await dependencies.budget.reserve({...context,reservationId:command.requestId,idempotencyKey:command.idempotencyKey,policyVersion:policy.policyVersion,modelKey:route.modelKey,providerKey:route.providerKey,priceVersion:route.priceVersion,currency:route.currency,estimatedMinor:BigInt(route.maximumEstimatedCostMinor),scopeKeys:command.scopeKeys});
 if(reservation.state!=="RESERVED")denied("GATEWAY_REQUEST_IN_PROGRESS");
 try{await dependencies.audit.record({...context,policyVersion:policy.policyVersion,modelKey:route.modelKey,providerKey:route.providerKey,reservationId:reservation.reservationId,state:"ADMITTED"});}catch{throw new Error("GATEWAY_AUDIT_UNAVAILABLE");}
 let providerResult:{text:string;receiptId:string;actualMinor:bigint};try{providerResult=await dependencies.credential.use(route.providerKey,secret=>dependencies.provider.invoke({providerKey:route.providerKey!,modelKey:route.modelKey!,messages:egress.payload!.messages,secret,requestId:command.requestId}));}catch{throw new Error("PROVIDER_UNAVAILABLE");}
 const reconciliation=await dependencies.budget.reconcile({...context,reservationId:reservation.reservationId,receiptId:providerResult.receiptId,actualMinor:providerResult.actualMinor});
 const result=Object.freeze({requestId:command.requestId,policyVersion:policy.policyVersion,catalogVersion:route.catalogVersion,priceVersion:route.priceVersion,reservationId:reservation.reservationId,modelKey:route.modelKey,providerKey:route.providerKey,state:"COMPLETED" as const,text:providerResult.text,actualMinor:providerResult.actualMinor,reconciliationState:reconciliation.state});
 try{await dependencies.audit.record({requestId:command.requestId,tenantId:command.tenantId,workspaceId:command.workspaceId,policyVersion:policy.policyVersion,modelKey:route.modelKey,providerKey:route.providerKey,reservationId:reservation.reservationId,state:result.state,actualMinor:providerResult.actualMinor.toString()});}catch{throw new Error("GATEWAY_AUDIT_UNAVAILABLE");}return result;
}
