import {randomUUID} from "node:crypto";import type {EgressException,EgressRule} from "../../domain/security/egress-guard.js";
type Result<Row>={rows:Row[]};type Client={query<Row=Record<string,unknown>>(sql:string,values?:readonly unknown[]):Promise<Result<Row>>;release():void};type Pool={connect():Promise<Client>};
export function createPostgresEgressRepository(pool:Pool){
 const scoped=async<T>(context:{tenantId:string;workspaceId:string},work:(client:Client)=>Promise<T>)=>{const client=await pool.connect();try{await client.query("BEGIN");await client.query("SELECT set_config('app.current_tenant_id',$1,true),set_config('app.current_workspace_id',$2,true)",[context.tenantId,context.workspaceId]);const value=await work(client);await client.query("COMMIT");return value;}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}};
 return Object.freeze({
  async loadPublishedRules():Promise<{version:number;rules:readonly EgressRule[]}>{const client=await pool.connect();try{const rows=(await client.query<{rule_id:string;ruleset_version:number;kind:string;detector:string;action:string;pattern?:string}>("SELECT rule_id,ruleset_version,kind,detector,action,pattern FROM egress_rule WHERE state='published' ORDER BY rule_id")).rows;const versions=new Set(rows.map(row=>Number(row.ruleset_version)));if(!rows.length||versions.size!==1)throw new Error("EGRESS_RULESET_INVALID");return {version:[...versions][0]!,rules:rows.map(row=>Object.freeze({ruleId:row.rule_id,kind:row.kind.toUpperCase(),detector:row.detector.toUpperCase(),action:row.action.toUpperCase(),...(row.pattern?{pattern:row.pattern}:{})}) as EgressRule)};}finally{client.release();}},
  async loadApplicableExceptions(context:{tenantId:string;workspaceId:string;providerKey:string;modelKey:string}):Promise<readonly EgressException[]>{return scoped(context,async client=>(await client.query<{exception_id:string;version:number;tenant_id:string;workspace_id:string;provider_key:string;model_key:string;pii_types:string[];owner:string;approver:string;valid_from:Date;expires_at:Date}>("SELECT * FROM egress_exception WHERE provider_key=$1 AND model_key=$2",[context.providerKey,context.modelKey])).rows.map(row=>Object.freeze({exceptionId:row.exception_id,version:Number(row.version),tenantId:row.tenant_id,workspaceId:row.workspace_id,providerKey:row.provider_key,modelKey:row.model_key,piiTypes:row.pii_types.map(value=>value.toUpperCase()) as EgressException["piiTypes"],owner:row.owner,approver:row.approver,validFrom:row.valid_from.toISOString(),expiresAt:row.expires_at.toISOString()})));},
  async audit(event:{requestId:string;tenantId:string;workspaceId:string;providerKey:string;modelKey:string;classification:string;ruleVersion:number;decision:"ALLOW"|"DENY";denyReasons:readonly string[];detections:Readonly<Record<string,number>>;exceptionId?:string}):Promise<void>{await scoped(event,client=>client.query("INSERT INTO egress_guard_audit(tenant_id,workspace_id,audit_id,request_id,provider_key,model_key,classification,rule_version,decision,deny_reasons,detections,exception_id,evaluated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10::jsonb,$11::jsonb,$12,clock_timestamp())",[event.tenantId,event.workspaceId,randomUUID(),event.requestId,event.providerKey,event.modelKey,event.classification,event.ruleVersion,event.decision.toLowerCase(),JSON.stringify(event.denyReasons),JSON.stringify(event.detections),event.exceptionId??null]).then(()=>undefined));},
 });
}
