import {randomUUID} from "node:crypto";
import type {CatalogModel} from "../../domain/catalog/model-router.js";
import type {Classification} from "../../domain/tenancy/workspace.js";
type Result<Row>={rows:Row[]};type Client={query<Row=Record<string,unknown>>(sql:string,values?:readonly unknown[]):Promise<Result<Row>>;release():void};type Pool={connect():Promise<Client>};
export function createPostgresModelCatalogRepository(pool:Pool,now:()=>Date=()=>new Date()){
 const transaction=async<T>(work:(client:Client)=>Promise<T>)=>{const client=await pool.connect();try{await client.query("BEGIN");const value=await work(client);await client.query("COMMIT");return value;}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}};
 return Object.freeze({
  async isProviderActive(providerKey:string){const client=await pool.connect();try{return (await client.query("SELECT 1 FROM model_provider_catalog WHERE provider_key=$1 AND status='active'",[providerKey])).rows.length===1;}finally{client.release();}},
  async loadFallbackGraph(){const client=await pool.connect();try{const rows=(await client.query<{model_key:string;fallback_model_key:string|null}>("SELECT m.model_key,f.fallback_model_key FROM model_catalog m LEFT JOIN model_fallback f ON f.model_key=m.model_key AND f.model_version=m.version WHERE m.status='active' ORDER BY m.model_key,f.position")).rows;const graph=new Map<string,string[]>();for(const row of rows){const values=graph.get(row.model_key)??[];graph.set(row.model_key,row.fallback_model_key?[...values,row.fallback_model_key]:values);}return graph;}finally{client.release();}},
  async publishProvider(input:{providerKey:string;version:number;status:"ACTIVE";maximumClassification:Classification;owner:string;justification:string;actorId:string;requestId:string}){await transaction(async client=>{await client.query("SELECT pg_advisory_xact_lock(hashtextextended($1,0))",[input.providerKey]);await client.query("UPDATE model_provider_catalog SET status='disabled' WHERE provider_key=$1 AND status IN ('active','deprecated')",[input.providerKey]);await client.query("INSERT INTO model_provider_catalog(provider_key,version,status,maximum_classification,owner,justification,published_at) VALUES($1,$2,'active',$3,$4,$5,$6)",[input.providerKey,input.version,input.maximumClassification,input.owner,input.justification,now().toISOString()]);await client.query("INSERT INTO model_catalog_audit(audit_id,request_id,actor_id,subject_key,subject_version,action,occurred_at) VALUES($1,$2,$3,$4,$5,'published',$6)",[randomUUID(),input.requestId,input.actorId,input.providerKey,input.version,now().toISOString()]);});},
  async publish(input:CatalogModel&{owner:string;justification:string;actorId:string;requestId:string}){await transaction(async client=>{await client.query("SELECT pg_advisory_xact_lock(hashtextextended($1,0))",[input.modelKey]);await client.query("UPDATE model_catalog SET status='disabled' WHERE model_key=$1 AND status IN ('active','deprecated')",[input.modelKey]);const inserted=await client.query(`INSERT INTO model_catalog(model_key,version,provider_key,provider_version,status,capabilities,maximum_classification,context_window_tokens,maximum_output_tokens,price_version,currency,input_minor_per_million_tokens,output_minor_per_million_tokens,route_priority,owner,justification,published_at)
    SELECT $1,$2,$3,p.version,'active',$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15 FROM model_provider_catalog p WHERE p.provider_key=$3 AND p.status='active'`,[input.modelKey,input.catalogVersion,input.providerKey,input.capabilities,input.maximumClassification,input.contextWindowTokens,input.maximumOutputTokens,input.priceVersion,input.currency,input.inputMinorPerMillionTokens,input.outputMinorPerMillionTokens,input.routePriority,input.owner,input.justification,now().toISOString()]);if((inserted as Result<unknown>&{rowCount?:number}).rowCount===0)throw new Error("PROVIDER_NOT_ACTIVE");for(const [index,key] of input.fallbackModelKeys.entries())await client.query("INSERT INTO model_fallback(model_key,model_version,fallback_model_key,position) VALUES($1,$2,$3,$4)",[input.modelKey,input.catalogVersion,key,index+1]);await client.query("INSERT INTO model_catalog_audit(audit_id,request_id,actor_id,subject_key,subject_version,action,occurred_at) VALUES($1,$2,$3,$4,$5,'published',$6)",[randomUUID(),input.requestId,input.actorId,input.modelKey,input.catalogVersion,now().toISOString()]);});},
 });
}
