import {randomUUID} from "node:crypto";
import type {SourceActor,SourceRepository} from "../../application/source/manage-source.js";
import type {SourceRegistryEntry} from "../../domain/source/source-registry.js";
type Result<Row>={rows:Row[];rowCount?:number|null};type Client={query<Row=Record<string,unknown>>(sql:string,values?:readonly unknown[]):Promise<Result<Row>>;release():void};type Pool={connect():Promise<Client>};
async function scoped<T>(pool:Pool,actor:Pick<SourceActor,"tenantId"|"workspaceId"|"userId">,operation:(client:Client)=>Promise<T>):Promise<T>{const client=await pool.connect();try{await client.query("BEGIN");await client.query("SELECT set_config('app.current_tenant_id',$1,true),set_config('app.current_workspace_id',$2,true),set_config('app.current_user_id',$3,true)",[actor.tenantId,actor.workspaceId,actor.userId]);const value=await operation(client);await client.query("COMMIT");return value;}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}}
type Row={source_id:string;tenant_id:string;workspace_id:string;name:string;purpose:string;source_type:string;origin_system_key:string;connector_key:string;owner_user_id?:string;owner_acceptance:"pending"|"accepted";classification?:any;schedule_mode:"manual"|"scheduled";sync_interval_seconds?:number;freshness_sla_seconds:number;retention_days:number;status:string;status_reason?:string;version:number;created_at:string;updated_at:string};
function domain(row:Row):SourceRegistryEntry{return{sourceId:row.source_id,tenantId:row.tenant_id,workspaceId:row.workspace_id,name:row.name,purpose:row.purpose,sourceType:row.source_type,originSystemKey:row.origin_system_key,connectorKey:row.connector_key,...(row.owner_user_id?{ownerUserId:row.owner_user_id}:{}),ownerAcceptance:row.owner_acceptance.toUpperCase() as any,...(row.classification?{classification:row.classification}:{}),schedule:row.schedule_mode==="manual"?{mode:"MANUAL"}:{mode:"SCHEDULED",intervalSeconds:row.sync_interval_seconds!},freshnessSlaSeconds:row.freshness_sla_seconds,retentionDays:row.retention_days,status:row.status.toUpperCase() as any,...(row.status_reason?{statusReason:row.status_reason}:{}),version:Number(row.version),createdAt:new Date(row.created_at).toISOString(),updatedAt:new Date(row.updated_at).toISOString()};}
const select="source_id,tenant_id,workspace_id,name,purpose,source_type,origin_system_key,connector_key,owner_user_id,owner_acceptance,classification,schedule_mode,sync_interval_seconds,freshness_sla_seconds,retention_days,status,status_reason,version,created_at,updated_at";
export function createPostgresSourceRepository(pool:Pool):SourceRepository{
 const record=async(client:Client,source:SourceRegistryEntry,meta:{actorId:string;requestId:string;eventType:string;reason?:string})=>{const attributes=JSON.stringify({source_id:source.sourceId,source_version:source.version,status:source.status,classification:source.classification??null,...(meta.reason?{reason_code:meta.reason}: {})});await client.query("INSERT INTO source_registry_audit(tenant_id,workspace_id,audit_id,request_id,actor_id,source_id,source_version,operation,attributes,occurred_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb,$10)",[source.tenantId,source.workspaceId,randomUUID(),meta.requestId,meta.actorId,source.sourceId,source.version,meta.eventType,attributes,source.updatedAt]);await client.query("INSERT INTO source_registry_outbox(tenant_id,workspace_id,event_id,event_type,request_id,actor_id,source_id,source_version,classification,status,occurred_at,attributes) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12::jsonb)",[source.tenantId,source.workspaceId,randomUUID(),meta.eventType,meta.requestId,meta.actorId,source.sourceId,source.version,source.classification??null,source.status.toLowerCase(),source.updatedAt,JSON.stringify(meta.reason?{reason_code:meta.reason}:{})]);};
 return{
  async create(source,meta){await scoped(pool,{...source,userId:meta.actorId},async client=>{await client.query("INSERT INTO source_registry(source_id,tenant_id,workspace_id,name,purpose,source_type,origin_system_key,connector_key,owner_user_id,owner_acceptance,classification,schedule_mode,sync_interval_seconds,freshness_sla_seconds,retention_days,status,version,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,'pending',$10,$11,$12,$13,$14,'draft',1,$15,$15)",[source.sourceId,source.tenantId,source.workspaceId,source.name,source.purpose,source.sourceType,source.originSystemKey,source.connectorKey,source.ownerUserId??null,source.classification??null,source.schedule.mode.toLowerCase(),source.schedule.mode==="SCHEDULED"?source.schedule.intervalSeconds:null,source.freshnessSlaSeconds,source.retentionDays,source.createdAt]);await record(client,source,meta);});},
  async load(actor,id){return scoped(pool,actor,async client=>{const row=(await client.query<Row>(`SELECT ${select} FROM source_registry WHERE tenant_id=$1 AND workspace_id=$2 AND source_id=$3`,[actor.tenantId,actor.workspaceId,id])).rows[0];return row?domain(row):undefined;});},
  async save(source,expected,meta){await scoped(pool,{...source,userId:meta.actorId},async client=>{const result=await client.query(`UPDATE source_registry SET owner_acceptance=$1,classification=$2,status=$3,status_reason=$4,version=$5,updated_at=$6 WHERE tenant_id=$7 AND workspace_id=$8 AND source_id=$9 AND version=$10`,[source.ownerAcceptance.toLowerCase(),source.classification??null,source.status.toLowerCase(),source.statusReason??null,source.version,source.updatedAt,source.tenantId,source.workspaceId,source.sourceId,expected]);if(result.rowCount!==1)throw new Error("SOURCE_VERSION_CONFLICT");await record(client,source,meta);});},
  async list(actor,cursor,limit=25){return scoped(pool,actor,async client=>(await client.query<Row>(`SELECT ${select} FROM source_registry WHERE tenant_id=$1 AND workspace_id=$2 AND ($3::uuid IS NULL OR source_id>$3) ORDER BY source_id LIMIT $4`,[actor.tenantId,actor.workspaceId,cursor??null,limit])).rows.map(domain));},
  async ownerIsEligible(actor,owner,classification){const rank={public:0,internal:1,confidential:2,restricted:3};return scoped(pool,actor,async client=>{const row=(await client.query<{classification_clearance:keyof typeof rank}>("SELECT classification_clearance FROM iam_workspace_membership WHERE tenant_id=$1 AND workspace_id=$2 AND user_id=$3 AND status='active'",[actor.tenantId,actor.workspaceId,owner])).rows[0];return Boolean(row&&rank[row.classification_clearance]>=rank[classification]);});}
 };}
