import {randomUUID} from "node:crypto";
import type {FastifyInstance,FastifyRequest} from "fastify";
import type {CreateSourceInput,SourceRegistryEntry} from "../../../domain/source/source-registry.js";
import type {SourceActor} from "../../../application/source/manage-source.js";

type AuthorizedActor=Omit<SourceActor,"requestId">;
export type SourceRouteServices=Readonly<{
 authorize(request:FastifyRequest):Promise<AuthorizedActor>;
 create(command:SourceActor&CreateSourceInput):Promise<SourceRegistryEntry>;
 list(actor:SourceActor,cursor?:string,limit?:number):Promise<readonly SourceRegistryEntry[]>;get(actor:SourceActor,id:string):Promise<SourceRegistryEntry>;
 submit(actor:SourceActor,id:string,version:number):Promise<SourceRegistryEntry>;accept(actor:SourceActor,id:string,version:number):Promise<SourceRegistryEntry>;activate(actor:SourceActor,id:string,version:number):Promise<SourceRegistryEntry>;
 transition(actor:SourceActor,id:string,version:number,status:"PAUSED"|"DISCONNECTED"|"ARCHIVED",reason:string):Promise<SourceRegistryEntry>;
}>;
const authorityKeys=new Set(["tenantId","tenant_id","workspaceId","workspace_id","userId","user_id","role","status","version","ownerAcceptance","ingestionEligible"]);
function requestId(request:FastifyRequest):string{const supplied=request.headers["x-request-id"];return typeof supplied==="string"&&/^[0-9a-f-]{36}$/i.test(supplied)?supplied:randomUUID();}
async function actor(request:FastifyRequest,services:SourceRouteServices):Promise<SourceActor>{return {...await services.authorize(request),requestId:requestId(request)};}
function expected(request:FastifyRequest):number{const value=request.headers["if-match"];if(typeof value!=="string"||!/^[1-9][0-9]*$/.test(value))throw new Error("SOURCE_PRECONDITION_REQUIRED");return Number(value);}
function idempotency(request:FastifyRequest):void{const value=request.headers["idempotency-key"];if(typeof value!=="string"||value.length<16||value.length>128)throw new Error("SOURCE_IDEMPOTENCY_REQUIRED");}
function safeBody(value:unknown):Record<string,unknown>{if(!value||typeof value!=="object"||Array.isArray(value))throw new Error("SOURCE_INVALID");const body=value as Record<string,unknown>;if(Object.keys(body).some(key=>authorityKeys.has(key)))throw new Error("SOURCE_CLIENT_AUTHORITY");return body;}
function present(source:SourceRegistryEntry){return{schema_version:"1.0.0",source_id:source.sourceId,tenant_id:source.tenantId,workspace_id:source.workspaceId,name:source.name,purpose:source.purpose,source_type:source.sourceType,origin_system_key:source.originSystemKey,connector_key:source.connectorKey,...(source.ownerUserId?{owner_user_id:source.ownerUserId}:{}),owner_acceptance:source.ownerAcceptance,...(source.classification?{classification:source.classification}:{}),schedule_mode:source.schedule.mode,...(source.schedule.mode==="SCHEDULED"?{sync_interval_seconds:source.schedule.intervalSeconds}:{}),freshness_sla_seconds:source.freshnessSlaSeconds,retention_days:source.retentionDays,status:source.status,...(source.statusReason?{status_reason:source.statusReason}:{}),ingestion_eligible:source.status==="ACTIVE"&&source.ownerAcceptance==="ACCEPTED",version:source.version,created_at:source.createdAt,updated_at:source.updatedAt};}
function mapping(error:unknown):{code:string;status:number}{const message=String(error);if(message.includes("DEPENDENCY_UNAVAILABLE"))return{code:"SOURCE_DEPENDENCY_UNAVAILABLE",status:503};if(message.includes("NOT_FOUND"))return{code:"SOURCE_NOT_FOUND",status:404};if(message.includes("VERSION_CONFLICT"))return{code:"SOURCE_VERSION_CONFLICT",status:409};if(message.includes("PRECONDITION"))return{code:"SOURCE_PRECONDITION_REQUIRED",status:428};if(message.includes("ACCESS_DENIED")||message.includes("OWNER_"))return{code:"SOURCE_ACCESS_DENIED",status:403};if(message.includes("INVALID")||message.includes("NOT_READY")||message.includes("TRANSITION")||message.includes("IDEMPOTENCY")||message.includes("CLIENT_AUTHORITY"))return{code:"SOURCE_INVALID",status:400};if(message.includes("IDENTITY")||message.includes("SESSION"))return{code:"SOURCE_UNAUTHENTICATED",status:401};return{code:"SOURCE_DEPENDENCY_UNAVAILABLE",status:503};}
async function handled(reply:any,operation:()=>Promise<unknown>,created=false){try{return reply.code(created?201:200).send(await operation());}catch(error){const mapped=mapping(error);return reply.code(mapped.status).send({code:mapped.code});}}

export function registerSourceRoutes(app:FastifyInstance,services:SourceRouteServices):void{
 app.post("/v1/admin/sources",async(request,reply)=>handled(reply,async()=>{idempotency(request);const body=safeBody(request.body);const context=await actor(request,services);return present(await services.create({...context,sourceId:String(body.source_id??""),name:String(body.name??""),purpose:String(body.purpose??""),sourceType:String(body.source_type??""),originSystemKey:String(body.origin_system_key??""),connectorKey:String(body.connector_key??""),...(body.owner_user_id?{ownerUserId:String(body.owner_user_id)}:{}),...(body.classification?{classification:body.classification as any}:{}),schedule:body.schedule as any,freshnessSlaSeconds:Number(body.freshness_sla_seconds),retentionDays:Number(body.retention_days)}));},true));
 app.get("/v1/admin/sources",async(request,reply)=>handled(reply,async()=>{const query=request.query as {cursor?:string;limit?:string};return (await services.list(await actor(request,services),query.cursor,query.limit?Number(query.limit):25)).map(present);}));
 app.get<{Params:{sourceId:string}}>("/v1/admin/sources/:sourceId",async(request,reply)=>handled(reply,async()=>present(await services.get(await actor(request,services),request.params.sourceId))));
 const action=(path:string,operation:(a:SourceActor,id:string,version:number)=>Promise<SourceRegistryEntry>)=>app.post<{Params:{sourceId:string}}>(path,async(request,reply)=>handled(reply,async()=>{idempotency(request);return present(await operation(await actor(request,services),request.params.sourceId,expected(request)));}));
 action("/v1/admin/sources/:sourceId/submit",services.submit);action("/v1/admin/sources/:sourceId/owner/accept",services.accept);action("/v1/admin/sources/:sourceId/activate",services.activate);
 for(const [suffix,status] of [["pause","PAUSED"],["disconnect","DISCONNECTED"],["archive","ARCHIVED"]] as const)app.post<{Params:{sourceId:string}}>(`/v1/admin/sources/:sourceId/${suffix}`,async(request,reply)=>handled(reply,async()=>{idempotency(request);const body=safeBody(request.body);return present(await services.transition(await actor(request,services),request.params.sourceId,expected(request),status,String(body.reason??"")));}));
}
