import assert from "node:assert/strict";import {test} from "node:test";import {executeModelRequest} from "../dist/application/gateway/execute-model-request.js";
const context={tenantId:"tenant",workspaceId:"workspace",userId:"user",deviceId:"device",sessionId:"session",requestId:"request"};
const policy={policyVersion:"policy-1",classification:"internal",allowedModels:["model-a"],allowedClassifications:["internal"],budgetScope:{currency:"BRL",remainingMinor:100},decision:"ALLOW"};
function fixture(overrides={}){const calls=[];return {calls,dependencies:{policy:{async resolve(){calls.push("policy");return policy;}},router:{async route(){calls.push("route");return {decision:"ALLOW",modelKey:"model-a",providerKey:"provider-a",catalogVersion:1,priceVersion:1,currency:"BRL",maximumEstimatedCostMinor:4};}},egress:{async prepare(){calls.push("egress");return {decision:"ALLOW",payload:{messages:[{role:"user",content:"masked"}]},ruleVersion:1};}},budget:{async reserve(){calls.push("budget");return {reservationId:"reservation",state:"RESERVED"};},async reconcile(){calls.push("reconcile");return {state:"COMMITTED"};}},credential:{async use(_provider,operation){calls.push("credential");return operation("secret-value");}},provider:{async invoke(input){calls.push("provider");assert.equal(input.secret,"secret-value");return {text:"answer",receiptId:"receipt",actualMinor:3n};}},audit:{async record(){calls.push("audit");}},...overrides}};}
test("gateway executes the approved fail-closed order and reconciles",async()=>{const value=fixture();const result=await executeModelRequest(value.dependencies,{...context,idempotencyKey:"1234567890abcdef",task:"chat",messages:[{role:"user",content:"email@example.test"}],requiredCapabilities:["CHAT"],inputTokens:10,maximumOutputTokens:20,scopeKeys:[{scopeType:"workspace",scopeId:"workspace"}]});assert.deepEqual(value.calls,["policy","route","egress","budget","audit","credential","provider","reconcile","audit"]);assert.equal(result.state,"COMPLETED");assert.equal(result.text,"answer");});
test("every security denial short-circuits before provider",async()=>{for(const point of ["policy","router","egress","budget"]){const value=fixture({[point]:point==="policy"?{async resolve(){value.calls.push(point);throw new Error("POLICY_DENIED");}}:point==="router"?{async route(){value.calls.push(point);return {decision:"DENY",denyReasons:["NO_ELIGIBLE_MODEL"]};}}:point==="egress"?{async prepare(){value.calls.push(point);return {decision:"DENY",denyReasons:["SECRET_DETECTED"]};}}:{async reserve(){value.calls.push(point);throw new Error("BUDGET_DENIED");},async reconcile(){throw new Error("unexpected");}}});await assert.rejects(()=>executeModelRequest(value.dependencies,{...context,idempotencyKey:"1234567890abcdef",task:"chat",messages:[{role:"user",content:"x"}],requiredCapabilities:["CHAT"],inputTokens:1,maximumOutputTokens:1,scopeKeys:[{scopeType:"workspace",scopeId:"workspace"}]}));assert.equal(value.calls.includes("provider"),false);}});
test("provider failure is sanitized and does not blindly reconcile or retry",async()=>{const value=fixture({provider:{async invoke(){value.calls.push("provider");throw new Error("provider leaked secret-value");}}});await assert.rejects(()=>executeModelRequest(value.dependencies,{...context,idempotencyKey:"1234567890abcdef",task:"chat",messages:[{role:"user",content:"x"}],requiredCapabilities:["CHAT"],inputTokens:1,maximumOutputTokens:1,scopeKeys:[{scopeType:"workspace",scopeId:"workspace"}]}),/PROVIDER_UNAVAILABLE/);assert.equal(value.calls.filter(x=>x==="provider").length,1);assert.equal(value.calls.includes("reconcile"),false);});
test("audit outage blocks before credential and provider",async()=>{const value=fixture({audit:{async record(){value.calls.push("audit");throw new Error("offline");}}});await assert.rejects(()=>executeModelRequest(value.dependencies,{...context,idempotencyKey:"1234567890abcdef",task:"chat",messages:[{role:"user",content:"x"}],requiredCapabilities:["CHAT"],inputTokens:1,maximumOutputTokens:1,scopeKeys:[{scopeType:"workspace",scopeId:"workspace"}]}),/GATEWAY_AUDIT_UNAVAILABLE/);assert.equal(value.calls.includes("credential"),false);assert.equal(value.calls.includes("provider"),false);});
test("replayed or ambiguous reservation never invokes provider again",async()=>{const value=fixture({budget:{async reserve(){value.calls.push("budget");return {reservationId:"reservation",state:"reserved"};},async reconcile(){throw new Error("unexpected");}}});await assert.rejects(()=>executeModelRequest(value.dependencies,{...context,idempotencyKey:"1234567890abcdef",task:"chat",messages:[{role:"user",content:"x"}],requiredCapabilities:["CHAT"],inputTokens:1,maximumOutputTokens:1,scopeKeys:[{scopeType:"workspace",scopeId:"workspace"}]}),/GATEWAY_REQUEST_IN_PROGRESS/);assert.equal(value.calls.includes("provider"),false);});
